name: Cypress Tests

on:
  push:
    branches:
      - main
      
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Cypress
        run:
            npm install cypress
            npx cypress verify

      - name: Run Cypress Tests
        run: npx cypress run
